---
title: "ERA5"
author: "Camille"
date: "2024-02-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Notes on ERA5
https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation

2m temperature: K
Surface solar radiation downwards: J/m2 --> x 86400 to obtain W/m2
Evaporation and potential evaporation: m of water equivalent
Precipitation: m of water per day -> x 1000 to obtain kg/m2/day


```{r land-masks}
land_mask <- raster("Masks/land_sea_mask_1degree.nc4") 
plot(land_mask)
land_mask.df <- as.data.frame(land_mask, xy = T) %>% setNames(c("lon","lat","lm")) # 0 if ocean, 1 if land


elev <- raster("Worldclim/wc2.1_10m/wc2.1_10m_elev.tif") 
elev.df <- elev %>% projectRaster(to = land_mask) %>% as.data.frame(xy = T) %>% setNames(c("lon","lat", "z"))


ipcc_regions <- shapefile("Masks/IPCC-WGI-reference-regions-v4.shp") %>% spTransform(crs("EPSG:4326")) 
ipcc_regions.raster <- ipcc_regions %>% rasterize(land_mask)
ipcc_regions.df <- as.data.frame(ipcc_regions.raster, xy = T) %>% setNames(c("lon","lat","Continent","Type","Name","Acronym"))

```

```{r land-mask-era5}
lmera <- raster("ERA5/land-sea-mask.nc") %>% rotate() %>% projectRaster(land_mask)
lmera.df <- as.data.frame(lmera, xy = T) %>% setNames(c("lon","lat","lm")) # 0 if ocean, 1 if land
```

```{r load-rasters}
pr <- raster("ERA5/total-precipitation.nc") %>% stack() %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

pr.df <- as.data.frame(pr, xy = T) %>% setNames(c("lon","lat","pr"))
write.table(pr.df, "ERA5/pr.df.txt")

tas <- raster("ERA5/temperature-2m.nc") %>% stack() %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas.df <- as.data.frame(tas, xy = T) %>% setNames(c("lon","lat","tas"))
write.table(tas.df, "ERA5/tas.df.txt")

rsds <- raster("ERA5/surface-short-wave-solar-radiation-downwards.nc") %>% stack() %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

rsds.df <- as.data.frame(rsds, xy = T) %>% setNames(c("lon","lat","rsds"))
write.table(rsds.df, "ERA5/rsds.df.txt")

wind <- raster("ERA5/wind10m.nc") %>% stack() %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

wind.df <- as.data.frame(wind, xy = T) %>% setNames(c("lon","lat","sfcWind")) # m/s
write.table(wind.df, "ERA5/wind.df.txt")

evaporation <- raster("ERA5/evaporation.nc") %>% stack() %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

evaporation.df <- as.data.frame(evaporation, xy = T) %>% setNames(c("lon","lat","evap"))
write.table(evaporation.df, "ERA5/evaporation.df.txt")

pot.evaporation <- raster("ERA5/potential-evaporation.nc") %>% stack() %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

pevap.df <- as.data.frame(pot.evaporation, xy = T) %>% setNames(c("lon","lat","pevap"))
write.table(pevap.df, "ERA5/pevap.df.txt")
```

```{r make-tas-min}
tas_jan <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 1, to = 349, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_jan.df <- as.data.frame(tas_jan, xy = T) %>% setNames(c("lon","lat","tas_01"))

tas_fev <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 2, to = 350, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_fev.df <- as.data.frame(tas_fev, xy = T) %>% setNames(c("lon","lat","tas_02"))

tas_mar <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 3, to = 351, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_mar.df <- as.data.frame(tas_mar, xy = T) %>% setNames(c("lon","lat","tas_03"))

tas_apr <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 4, to = 352, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_apr.df <- as.data.frame(tas_apr, xy = T) %>% setNames(c("lon","lat","tas_04"))

tas_may <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 5, to = 353, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_may.df <- as.data.frame(tas_may, xy = T) %>% setNames(c("lon","lat","tas_05"))

tas_jun <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 6, to = 354, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_jun.df <- as.data.frame(tas_jun, xy = T) %>% setNames(c("lon","lat","tas_06"))

tas_jul <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 7, to = 355, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_jul.df <- as.data.frame(tas_jul, xy = T) %>% setNames(c("lon","lat","tas_07"))

tas_aug <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 8, to = 356, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_aug.df <- as.data.frame(tas_aug, xy = T) %>% setNames(c("lon","lat","tas_08"))

tas_sep <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 9, to = 357, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_sep.df <- as.data.frame(tas_sep, xy = T) %>% setNames(c("lon","lat","tas_09"))

tas_oct <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 10, to = 358, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_oct.df <- as.data.frame(tas_oct, xy = T) %>% setNames(c("lon","lat","tas_10"))

tas_nov <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 11, to = 359, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_nov.df <- as.data.frame(tas_nov, xy = T) %>% setNames(c("lon","lat","tas_11"))

tas_dec <- raster("ERA5/temperature-2m.nc") %>% stack(bands = seq(from = 12, to = 3360, by = 12)) %>% raster::mean(na.rm = T) %>% raster::rotate() %>% projectRaster(land_mask)

tas_dec.df <- as.data.frame(tas_dec, xy = T) %>% setNames(c("lon","lat","tas_12"))

```

```{r merge-tas-month }


tas_month <- tas_jan.df %>% 
  merge(tas_fev.df, by =c("lon","lat")) %>%
  merge(tas_mar.df, by =c("lon","lat")) %>%
  merge(tas_apr.df, by =c("lon","lat")) %>%
  merge(tas_may.df, by =c("lon","lat")) %>%n
  merge(tas_jun.df, by =c("lon","lat")) %>%
  merge(tas_jul.df, by =c("lon","lat")) %>%
  merge(tas_aug.df, by =c("lon","lat")) %>%
  merge(tas_sep.df, by =c("lon","lat")) %>%
  merge(tas_oct.df, by =c("lon","lat")) %>%
  merge(tas_nov.df, by =c("lon","lat")) %>%
  merge(tas_dec.df, by =c("lon","lat"))

tas_month$tas_min <- apply(select(tas_month,c("tas_01", "tas_02", "tas_03", "tas_04", "tas_05", "tas_06", "tas_07", "tas_08", "tas_09", "tas_10", "tas_11", "tas_12")), 1, FUN = min, na.rm = T)

write.table(tas_month, "ERA5/tas_month.txt")
```

```{r merge-dfs}
pr.df <- read.table("ERA5/pr.df.txt")
tas.df <- read.table("ERA5/tas.df.txt")
tas_month.df <- read.table("ERA5/tas_month.txt")
rsds.df <- read.table("ERA5/rsds.df.txt")
wind.df <- read.table("ERA5/wind.df.txt")
evaporation.df <- read.table("ERA5/evaporation.df.txt")
pevap.df <- read.table("ERA5/pevap.df.txt")

era5 <- pr.df %>%
  merge(tas.df, by = c("lon","lat")) %>%
  merge(tas_month, by = c("lon","lat")) %>%
  merge(rsds.df, by = c("lon","lat")) %>%
  merge(wind.df, by = c("lon","lat")) %>%
  merge(evaporation.df, by = c("lon","lat")) %>%
  merge(pevap.df, by = c("lon","lat")) %>% 
  merge(elev.df, by = c("lon","lat")) %>%
  merge(ipcc_regions.df, by = c("lon","lat")) %>%
  merge(land_mask.df, by = c("lon","lat")) %>%
  filter(lm == 1) %>%
  mutate(model = "historical", period = "1970_2000", source = "ERA5")

era5$pr <- era5$pr * 1000 / (60*60*24) # from m/day to mm/d to mm/s = kg/m2/s
era5$rsds <- era5$rsds / (60*60*24) # from J/m2 to W/m2 (J/m2 accumulated over a month)

write.table(era5, "era5.txt")
```

```{r aridity-index}

# Martonne
era5$AIm <- with(era5,pr*60*60*24*365/(tas-273.15+10)) # convert pr to mm/y, tas to Ceslsius
breaks.martonne <- c(0,5,10,20,"30","40",Inf)
cat.martonne <- c("[0,5]" = "Desert", "(5,10]"= "Arid", "(10,20]" = "Semi-arid","(20,30]" = "Temperate", "(30,40]" = "Humid", "(40,Inf]" = "Forest")

era5$cat.AIm <- era5$AIm %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)

# Unesco

era5$P <- with(era5, 101.3 * ((293-0.0065*z)/293)^(5.26))
era5$es <- with(era5, ifelse((tas-273.15) > 0, 0.61078*exp(17.27*(tas-273.15)/((tas-273.15)+237.3)),  0.61078*exp(21.875*(tas-273.15)/((tas-273.15)+265.5)))) # saturation vapor pressure Monteith-Unsworth pour >0, Murray pour T < 0
era5$delta <- with(era5, 4098*es/((tas-273.15)+237.3)^2) #slope vapor pressure
era5$gamma <- with(era5, 0.00163*P/(2.501-52.6361e-3*(tas-273.15))) #psychrometric constant
era5$ea <- with(era5, with(era5, ifelse((tas_min-273.15) > 0, 0.61078*exp(17.27*(tas_min-273.15)/((tas_min-273.15)+237.3)),  0.61078*exp(21.875*(tas_min-273.15)/((tas_min-273.15)+265.5))))) # actual vapor pressur; when relative humidity is not available, ea is obtained by estimating that when the air temp is close to Tmin, it is nearly saturated
era5$ET0 <-with(era5, ((0.408*delta*(rsds*86400*1e-6)+gamma*900/((tas-273.15)+273)*sfcWind*(es-ea))/(delta+gamma*(1+0.34*sfcWind)))) # Evapotranspiration, G considered to be negligible. in mm/day. Irradiation is in W/m2 and is converted to MJ/m2/day
era5$AIu <- with(era5, pr*60*60*24*365/(ET0*365))

breaks.unesco <- c(-Inf,0.03,0.2,0.5,0.65,Inf)
cat.unesco <- c("(-Inf,0.03]"= "Hyperarid", "(0.03,0.2]" = "Arid", "(0.2,0.5]" = "Semi-arid", "(0.5,0.65]" = "Dry subhumid","(0.65, Inf]" = "Humid")

# save
era5$cat.AIu <- era5$AIu %>% cut(breaks = breaks.unesco) %>% 
  revalue(cat.unesco)

```

```{r plot}
ggplot() + geom_raster(data = era5, aes(x=lon, y = lat,  fill = cat.AIu))+
  scale_fill_manual(values = col.cat)+
  theme_void()+
  theme(legend.position = "bottom")

```

