---
title: "Historical AI"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
date: "2023-09-13"
bibliography: AI.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, error = F, fig.align = "center", collapse = T)
```

```{r libraries}
library(raster)
library(dplyr)
library(ggplot2)
library(plyr)
library(viridisLite)
library(sf)
library(stringr)
colorvec <- viridis(n = 7, direction = -1)
```

# De Martonne

```{r common-data}
land_mask <- raster("ATLAS-v1.6/SantanderMetGroup-ATLAS-d75f71f/reference-grids/land_sea_mask_1degree.nc4")
land_mask.df <- as.data.frame(land_mask, xy = T) %>% setNames(c("lon","lat","lm")) # 0 if ocean, 1 if land

ipcc_regions <- shapefile("ATLAS-v1.6/SantanderMetGroup-ATLAS-d75f71f/reference-regions/IPCC-WGI-reference-regions-v4.shp") %>% spTransform(crs("EPSG:4326"))
ext <- floor(extent(ipcc_regions))
rr <- raster(ext, res = 1)
ripcc_regions <- rasterize(ipcc_regions, rr)
ipcc_regions.df <- as.data.frame(ripcc_regions, xy = T) %>% setNames(c("lon","lat","Continent","Type","Name","Acronym"))
plot(ripcc_regions)

elev <- raster("elevation_100KMmn_GMTEDmn.tif") %>% projectRaster(to = ripcc_regions)

breaks.martonne <- c(0,10,20,24,28,35,55,Inf)
cat.martonne <- c("[0,10]"= "Dry", "(10,20]" = "Semi-dry","(20,24]" = "Meditarranean", "(24,28]" = "Semi-humid", "(28,35]" = "Humid","(35,55]" = "Very humid (a)", "(55,Inf]" = "Very humid (b)")
cat.m <- c("Dry", "Semi-dry","Meditarranean", "Semi-humid", "Humid", "Very humid (a)", "Very humid (b)")
col.cat <- c("Dry" = colorvec[1], "Semi-dry"= colorvec[2],"Meditarranean"= colorvec[3], "Semi-humid" = colorvec[4], "Humid"= colorvec[5],"Very humid (a)"= colorvec[6], "Very humid (b)" = colorvec[7])
```

IPCC regions from @Iturbide2020
Elevation from https://www.earthenv.org/topography 

## Models 1 file

```{r AI-De-Martonne}
list.temp <- list.files(path = "CMIP6/historical/ts", pattern = ".nc", full.names = T)
list.pre <- list.files(path = "CMIP6/historical/pr", pattern = ".nc", full.names = T)


for(i in 1:length(list.temp)){
  #get model name
  mname <- sub(pattern = ".*Amon_*", x = list.temp[i], replacement = "") %>% sub(replacement = "", pattern = "_historical*.*")
  
  # get variables for period 1: 1850-1880
  tavg1 <- raster::stack(list.temp[i], bands = c(1:360)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg1 <- raster::stack(list.pre[i], bands = c(1:360)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI1 <- (pavg1*12*60*60*365)/((tavg1-273)+10)
  extent(AI1) <- c(-180,180,-90,90)
  AI1 <- projectRaster(from = AI1, to = ripcc_regions)
  writeRaster(AI1, filename = paste("CMIP6/historical/Martonne/AI",mname,"1850-1880.nc", sep = "_"), format = "CDF", overwrite = T)
  
  
  # converts to DF and compute categories per IPCC region
  AI1.df <- as.data.frame(AI1, xy = T) %>% setNames(c("lon","lat","AI"))
  AI1.df$cat.AI <- AI1.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot1 <- merge(AI1.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot1.land <- subset(tot1,lm == 1)
  tot1.land$model <- mname
  write.table(tot1.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1850-1880.csv", sep = "_"))
  sorted.df1 <- table(tot1.land$cat.AI,tot1.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1850","_")))
  write.table(sorted.df1, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1850-1880.csv", sep = "_"))
  
  g1 <- ggplot(tot1.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat)+  labs(title = paste(mname,"1850-1880", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1850-1880.png", sep = "_"),g1, path = "CMIP6/historical/Martonne/")


  # get variables for period 2: 1984-2014
  tavg2 <- raster::stack(list.temp[i], bands = c(1621:1980)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg2 <- raster::stack(list.pre[i], bands = c(1621:1980)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI2 <- (pavg2*12*60*60*365)/((tavg2-273)+10)
  extent(AI2) <- c(-180,180,-90,90)
  AI2 <- projectRaster(from = AI2, to = ripcc_regions)
  writeRaster(AI2, filename = paste("CMIP6/historical/Martonne/AI",mname,"1984-2014.nc", sep = "_"), format = "CDF", overwrite = T)
  
  # converts to DF and compute categories per IPCC region
  AI2.df <- as.data.frame(AI2, xy = T) %>% setNames(c("lon","lat","AI"))
  AI2.df$cat.AI <- AI2.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot2 <- merge(AI2.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot2.land <- subset(tot2,lm == 1)
  tot2.land$model <- mname
  write.table(tot2.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1984-2014.csv", sep = "_"))
  sorted.df2 <- table(tot2.land$cat.AI,tot2.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1984", sep = "_")))
    write.table(sorted.df2, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1984-2014.csv", sep = "_"))
  
  g2 <- ggplot(tot2.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat)+  labs(title = paste(mname,"1984-2014", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1984-2014.png", sep = "_"),g2, path = "CMIP6/historical/Martonne/")
  
}



```

```{r other-t-ime-periods}
list.temp <- list.files(path = "CMIP6/historical/ts", pattern = ".nc", full.names = T)
list.pre <- list.files(path = "CMIP6/historical/pr", pattern = ".nc", full.names = T)

for(i in 1:length(list.temp)){
  #get model name
  mname <- sub(pattern = ".*Amon_*", x = list.temp[i], replacement = "") %>% sub(replacement = "", pattern = "_historical*.*")

  # get variables for period 0: 1850-1880
  tavg0 <- raster::stack(list.temp[i], bands = c(1:360)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg0 <- raster::stack(list.pre[i], bands = c(1:360)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI0 <- (pavg0*12*60*60*365)/((tavg0-273)+10)
  extent(AI0) <- c(-180,180,-90,90)
  AI0 <- projectRaster(from = AI0, to = ripcc_regions)
  writeRaster(AI0, filename = paste("CMIP6/historical/Martonne/AI",mname,"1850-1880.nc", sep = "_"), format = "CDF", overwrite = T)
  
  
  # converts to DF and compute categories per IPCC region
  AI0.df <- as.data.frame(AI0, xy = T) %>% setNames(c("lon","lat","AI"))
  AI0.df$cat.AI <- AI0.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot0 <- merge(AI0.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot0.land <- subset(tot0,lm == 1)
  tot0.land$model <- mname
  write.table(tot0.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1850-1880.csv", sep = "_"))
  sorted.df0 <- table(tot0.land$cat.AI,tot1.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1850","_")))
  write.table(sorted.df0, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1850-1880.csv", sep = "_"))
  
  g0 <- ggplot(tot0.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = paste(mname,"1850-1880", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1850-1880.png", sep = "_"),g0, path = "CMIP6/historical/Martonne/")
  
  # get variables for period 1: 1880-1910
  tavg1 <- raster::stack(list.temp[i], bands = c(361:720)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg1 <- raster::stack(list.pre[i], bands = c(361:720)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI1 <- (pavg1*12*60*60*365)/((tavg1-273)+10)
  extent(AI1) <- c(-180,180,-90,90)
  AI1 <- projectRaster(from = AI1, to = ripcc_regions)
  writeRaster(AI1, filename = paste("CMIP6/historical/Martonne/AI",mname,"1880-1910.nc", sep = "_"), format = "CDF", overwrite = T)
  
  
  # converts to DF and compute categories per IPCC region
  AI1.df <- as.data.frame(AI1, xy = T) %>% setNames(c("lon","lat","AI"))
  AI1.df$cat.AI <- AI1.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot1 <- merge(AI1.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot1.land <- subset(tot1,lm == 1)
  tot1.land$model <- mname
  write.table(tot1.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1880-1910.csv", sep = "_"))
  sorted.df1 <- table(tot1.land$cat.AI,tot1.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1880","_")))
  write.table(sorted.df1, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1880-1910.csv", sep = "_"))
  
  g1 <- ggplot(tot1.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = paste(mname,"1880-1910", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1880-1910.png", sep = "_"),g1, path = "CMIP6/historical/Martonne/")


  # get variables for period 2: 1910-1940
  tavg2 <- raster::stack(list.temp[i], bands = c(721:1080)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg2 <- raster::stack(list.pre[i], bands = c(721:1080)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI2 <- (pavg2*12*60*60*365)/((tavg2-273)+10)
  extent(AI2) <- c(-180,180,-90,90)
  AI2 <- projectRaster(from = AI2, to = ripcc_regions)
  writeRaster(AI2, filename = paste("CMIP6/historical/Martonne/AI",mname,"1910-1940.nc", sep = "_"), format = "CDF", overwrite = T)
  
  # converts to DF and compute categories per IPCC region
  AI2.df <- as.data.frame(AI2, xy = T) %>% setNames(c("lon","lat","AI"))
  AI2.df$cat.AI <- AI2.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot2 <- merge(AI2.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot2.land <- subset(tot2,lm == 1)
  tot2.land$model <- mname
  write.table(tot2.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1910-1940.csv", sep = "_"))
  sorted.df2 <- table(tot2.land$cat.AI,tot2.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1910", sep = "_")))
    write.table(sorted.df2, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1910-1940.csv", sep = "_"))
  
  g2 <- ggplot(tot2.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = paste(mname,"1910-1940", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1910-1940.png", sep = "_"),g2, path = "CMIP6/historical/Martonne/")
  
    # get variables for period 3: 1940-1970
  tavg3 <- raster::stack(list.temp[i], bands = c(1081:1440)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg3 <- raster::stack(list.pre[i], bands = c(1081:1440)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI3 <- (pavg3*12*60*60*365)/((tavg3-273)+10)
  extent(AI3) <- c(-180,180,-90,90)
  AI3 <- projectRaster(from = AI3, to = ripcc_regions)
  writeRaster(AI3, filename = paste("CMIP6/historical/Martonne/AI",mname,"1940-1970.nc", sep = "_"), format = "CDF", overwrite = T)
  
  # converts to DF and compute categories per IPCC region
  AI3.df <- as.data.frame(AI3, xy = T) %>% setNames(c("lon","lat","AI"))
  AI3.df$cat.AI <- AI3.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot3 <- merge(AI3.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot3.land <- subset(tot3,lm == 1)
  tot3.land$model <- mname
  write.table(tot3.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1940-1970.csv", sep = "_"))
  sorted.df3 <- table(tot3.land$cat.AI,tot3.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1940", sep = "_")))
    write.table(sorted.df3, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1940-1970.csv", sep = "_"))
  
  g3 <- ggplot(tot3.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = paste(mname,"1940-1970", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1940-1970.png", sep = "_"),g3, path = "CMIP6/historical/Martonne/")
  
    # get variables for period 4: 1970-2000
  tavg4 <- raster::stack(list.temp[i], bands = c(1441:1800)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg4 <- raster::stack(list.pre[i], bands = c(1441:1800)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI4 <- (pavg4*12*60*60*365)/((tavg4-273)+10)
  extent(AI4) <- c(-180,180,-90,90)
  AI4 <- projectRaster(from = AI4, to = ripcc_regions)
  writeRaster(AI4, filename = paste("CMIP6/historical/Martonne/AI",mname,"1970-2000.nc", sep = "_"), format = "CDF", overwrite = T)
  
  # converts to DF and compute categories per IPCC region
  AI4.df <- as.data.frame(AI4, xy = T) %>% setNames(c("lon","lat","AI"))
  AI4.df$cat.AI <- AI4.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot4 <- merge(AI4.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot4.land <- subset(tot4,lm == 1)
  tot4.land$model <- mname
  write.table(tot4.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1970-2000.csv", sep = "_"))
  sorted.df4 <- table(tot4.land$cat.AI,tot4.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1970", sep = "_")))
    write.table(sorted.df4, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1970-2000.csv", sep = "_"))
  
  g4 <- ggplot(tot4.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = paste(mname,"1970-2000", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1970-2000.png", sep = "_"),g4, path = "CMIP6/historical/Martonne/")
  
    # get variables for end period: 1984-2014
  tavg5 <- raster::stack(list.temp[i], bands = c(1621:1980)) %>% mean(na.rm = T) %>% reclassify(cbind(-Inf,(-10+273),NA))   #mean annual temperature for the period in K
  pavg5 <- raster::stack(list.pre[i], bands = c(1621:1980)) %>% mean(na.rm = T) #monthly average of daily precipitation in kg/m2/s-1. Converted to mm / month by 1) compute the global average, 2) multiply by 12 to obtain annual average, 3) multiply by 60*60*365 to obtain annual values
  
  #computes and save AI raster
  AI5 <- (pavg5*12*60*60*365)/((tavg5-273)+10)
  extent(AI5) <- c(-180,180,-90,90)
  AI5 <- projectRaster(from = AI5, to = ripcc_regions)
  writeRaster(AI5, filename = paste("CMIP6/historical/Martonne/AI",mname,"1984-2014.nc", sep = "_"), format = "CDF", overwrite = T)
  
  # converts to DF and compute categories per IPCC region
  AI5.df <- as.data.frame(AI5, xy = T) %>% setNames(c("lon","lat","AI"))
  AI5.df$cat.AI <- AI5.df$AI %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)
  tot5 <- merge(AI5.df, ipcc_regions.df, by = c("lon","lat")) %>% merge(land_mask.df, by = c("lon","lat"))
  tot5.land <- subset(tot5,lm == 1)
  tot5.land$model <- mname
  write.table(tot5.land, file = paste("CMIP6/historical/Martonne/AI",mname,"1984-2014.csv", sep = "_"))
  sorted.df5 <- table(tot5.land$cat.AI,tot2.land$Acronym) %>% as.data.frame() %>% setNames(c("cat.AI","Region",paste(mname,"1984", sep = "_")))
    write.table(sorted.df5, file = paste("CMIP6/historical/Martonne/region_AI",mname,"1984-2014.csv", sep = "_"))
  
  g5 <- ggplot(tot5.land)+geom_raster(aes(x=lon, y = lat, fill = cat.AI))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = paste(mname,"1984-2014", sep = "_"), fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
  ggsave(filename = paste(mname,"AI_Martonne_1984-2014.png", sep = "_"),g5, path = "CMIP6/historical/Martonne/")
}

```


```{r plots-all-martonne}
#load files
list.region.1850 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "region_AI*.*1850-1880.csv", full.names = T)
list.region.1880 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "region_AI*.*1880-1910.csv", full.names = T)
list.region.1910 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "region_AI*.*1910-1940.csv", full.names = T)
list.region.1940 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "region_AI*.*1940-1970.csv", full.names = T)
list.region.1970 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "region_AI*.*1970-2000.csv", full.names = T)
list.region.1984 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "region_AI*.*1984-2014.csv", full.names = T)

list.tot.df.1850 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "1850-1880.csv", full.names = T) %>% setdiff(list.region.1850)  %>% lapply(read.table, header = T)
list.tot.df.1880 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "1880-1910.csv", full.names = T) %>% setdiff(list.region.1880)  %>% lapply(read.table, header = T)
list.tot.df.1910 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "1910-1940.csv", full.names = T) %>% setdiff(list.region.1910)  %>% lapply(read.table, header = T)
list.tot.df.1940 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "1940-1970.csv", full.names = T) %>% setdiff(list.region.1940)  %>% lapply(read.table, header = T)
list.tot.df.1970 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "1970-2000.csv", full.names = T) %>% setdiff(list.region.1970)  %>% lapply(read.table, header = T)
list.tot.df.1984 <- list.files(path = "CMIP6/historical/Martonne/", pattern = "1984-2014.csv", full.names = T) %>% setdiff(list.region.1984)  %>% lapply(read.table, header = T)


# 1850-1880
df_1850 <- do.call("rbind", list.tot.df.1850)
df_1850$cat.AI <- df_1850$cat.AI

sum_1850 <- df_1850 %>% group_by(lon,lat,Acronym) %>%  
                        dplyr::summarise(AI.avg = mean(AI, na.rm = T), AI.sd = sd(AI, na.rm = T),
                                        cat.AI.maj =  names(which.max(table(cat.AI, exclude = NULL))),
                                        agreement = str_count(string = cat.AI, pattern = cat.AI.maj)/11) %>% 
                      as.data.frame()
sum_1850$cat.AI <- sum_1850$AI.avg %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)

sum_1850$cat.AI.maj <- sum_1850$cat.AI.maj %>% factor() %>% ordered(cat.m)

ggplot()+geom_raster(data = sum_1850, aes(x=lon, y = lat, fill = cat.AI.maj))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = "AI 1850-1880", fill = "")+
   geom_point(data = filter(sum_diff, agreement > 0.6), aes(x = lon, y = lat), col = "black", shape = "'")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))

# 1880-1910
df_1880 <- do.call("rbind", list.tot.df.1880)
df_1880$cat.AI <- df_1880$cat.AI

sum_1880 <- df_1880 %>% group_by(lon,lat,Acronym) %>%  
                        dplyr::summarise(AI.avg = mean(AI, na.rm = T), AI.sd = sd(AI, na.rm = T),
                                        cat.AI.maj =  names(which.max(table(cat.AI, exclude = NULL))),
                                        agreement = str_count(string = cat.AI, pattern = cat.AI.maj)/11) %>% 
                      as.data.frame()
sum_1880$cat.AI <- sum_1880$AI.avg %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)

sum_1880$cat.AI.maj <- sum_1880$cat.AI.maj %>% factor() %>% ordered(cat.m)

ggplot()+geom_raster(data = sum_1880, aes(x=lon, y = lat, fill = cat.AI.maj))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = "AI 1880-1910", fill = "")+
   geom_point(data = filter(sum_diff, agreement > 0.6), aes(x = lon, y = lat), col = "black", shape = "'")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))

# 1910-1940
df_1910 <- do.call("rbind", list.tot.df.1910)
df_1910$cat.AI <- df_1910$cat.AI

sum_1910 <- df_1910 %>% group_by(lon,lat,Acronym) %>%  
                        dplyr::summarise(AI.avg = mean(AI, na.rm = T), AI.sd = sd(AI, na.rm = T),
                                        cat.AI.maj =  names(which.max(table(cat.AI, exclude = NULL))),
                                        agreement = str_count(string = cat.AI, pattern = cat.AI.maj)/11) %>% 
                      as.data.frame()
sum_1910$cat.AI <- sum_1910$AI.avg %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)

sum_1910$cat.AI.maj <- sum_1910$cat.AI.maj %>% factor() %>% ordered(cat.m)

ggplot()+geom_raster(data = sum_1910, aes(x=lon, y = lat, fill = cat.AI.maj))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = "AI 1910-1940", fill = "")+
   geom_point(data = filter(sum_diff, agreement > 0.6), aes(x = lon, y = lat), col = "black", shape = "'")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))


# 1940-1970
df_1940 <- do.call("rbind", list.tot.df.1940)
df_1940$cat.AI <- df_1940$cat.AI

sum_1940 <- df_1940 %>% group_by(lon,lat,Acronym) %>%  
                        dplyr::summarise(AI.avg = mean(AI, na.rm = T), AI.sd = sd(AI, na.rm = T),
                                        cat.AI.maj =  names(which.max(table(cat.AI, exclude = NULL))),
                                        agreement = str_count(string = cat.AI, pattern = cat.AI.maj)/11) %>% 
                      as.data.frame()
sum_1940$cat.AI <- sum_1940$AI.avg %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)

sum_1940$cat.AI.maj <- sum_1910$cat.AI.maj %>% factor() %>% ordered(cat.m)

ggplot()+geom_raster(data = sum_1910, aes(x=lon, y = lat, fill = cat.AI.maj))+
    scale_fill_manual(values = col.cat, na.value = "grey90")+  labs(title = "AI 1910-1940", fill = "")+
   geom_point(data = filter(sum_diff, agreement > 0.6), aes(x = lon, y = lat), col = "black", shape = "'")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))







diff.df <- merge(df_1850, df_1984, by = c("lon","lat","Continent","Type","Name","Acronym","model","lm")) %>% mutate(diff.AI = AI.y - AI.x, sign.diff = ifelse(diff.AI > 0,"+","-"))
sum_diff <- diff.df %>% group_by(lon,lat,Acronym) %>% dplyr::summarise(diff.AI = mean(diff.AI, na.rm = T) , change.plus = sum(sign.diff == "+", na.rm = T), change.minus = sum(sign.diff == "-", na.rm = T), agreement = max(change.plus,change.minus)/11) %>% as.data.frame()
sum_diff$cat.diff <- sum_diff$diff.AI %>% cut(breaks = c(-Inf,-20,-10,0,10,20,Inf), include.lowest = T) 


ggplot()+geom_raster(data = sum_diff, aes(x=lon, y = lat, fill = cat.diff))+
    geom_point(data = filter(sum_diff, agreement > 0.6), aes(x = lon, y = lat), col = "black", shape = "'")+
    scale_fill_viridis_d(direction = -1, na.value = "grey90")+labs(title = "Change in AI 1984-2014 compared to 1850-1880", fill = "")+
    theme_void(base_size = 10)+theme(legend.position = "bottom")+guides(fill = guide_legend(nrow = 2))
``` 


```{r compare-periods}
list.tables <- list.files(path = "CMIP6/historical/Martonne", pattern = "region_AI", full.names = T) %>% 
  lapply(read.table, header = T)
df <- do.call("merge",list.tables) %>% mutate(diff = t1984-t1850)

ggplot(df, aes(x=Region))+geom_col(aes(y = t1850, fill = cat.AI))+
  geom_col(aes(y = -t1984, fill = cat.AI))+
  scale_fill_manual(values = col.cat)+ 
  theme_bw(base_size = 10)+theme(legend.position = "bottom")
ggplot(df, aes(x=Region))+geom_col(aes(y = diff, fill = cat.AI))+
  scale_fill_manual(values = col.cat)+ 
  theme_bw(base_size = 10)+theme(legend.position = "bottom")


list.rasters <- list.files(path = "CMIP6/historical/Martonne", pattern = "AI_*.nc", full.names = T)
```