---
title: "Maps AWI"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
date: "2023-12-13"
bibliography: AI.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE, fig.align = "center", collapse = T)
```

```{r libraries}
library(raster)
library(dplyr)
library(ggplot2)
library(viridisLite)
library(sf)
library(stringr)
```

```{r masks}
cmcc <- raster("/bettik/crapartc/CMIP6/ts/ts_Amon_CMCC-CM2-SR5_historical_r1i1p1f1_gn_185001-201412.nc")
crs(cmcc) <- "EPSG:4326"
cmcc.df <- as.data.frame(ex_raster, xy = T)

land_mask <- raster("Aridity/Masks/land_sea_mask_1degree.nc4") 
extent(land_mask) <- extent(cmcc)
land_mask <-  projectRaster(from = land_mask, to = cmcc)
land_mask.df <- as.data.frame(land_mask, xy = T) %>% setNames(c("lon","lat","lm")) # 0 if ocean, 1 if land

ipcc_regions <- shapefile("Aridity/Masks/IPCC-WGI-reference-regions-v4.shp") %>% spTransform(crs("EPSG:4326")) 
ipcc_regions.raster <- ipcc_regions %>% rasterize(cmcc)
ipcc_regions.df <- as.data.frame(ipcc_regions.raster, xy = T) %>% setNames(c("lon","lat","Continent","Type","Name","Acronym"))
#ipcc_regions.sf <- st_as_sf(ipcc_regions.raster)
```

```{r awi-annual-long}
awi_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

awi_land <- merge(awi_annual, land_mask.df, by = c("lon", "lat")) 
awi_ipcc <- merge(awi_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(awi_ipcc, "Aridity/CMIP6/awi.ts_ipcc.txt")
```

```{r awi-monthly-long}
awi_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/awi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

awim_land <- merge(awi_monthly, land_mask.df, by = c("lon", "lat")) 
awim_ipcc <- merge(awim_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(awim_ipcc, "Aridity/CMIP6/awim.ts_ipcc.txt")
```

```{r bcc-annual-long}
bcc_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

bcc_land <- merge(bcc_annual, land_mask.df, by = c("lon", "lat")) 
bcc_ipcc <- merge(bcc_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(bcc_ipcc, "Aridity/CMIP6/bcc.ts_ipcc.txt")
```
```{r bcc-monthly-long}
bcc_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/bcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

bccm_land <- merge(bcc_monthly, land_mask.df, by = c("lon", "lat")) 
bccm_ipcc <- merge(bccm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(bccm_ipcc, "Aridity/CMIP6/bccm.ts_ipcc.txt")
```
```{r cams-annual-long}
cams_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

cams_land <- merge(cams_annual, land_mask.df, by = c("lon", "lat")) 
cams_ipcc <- merge(cams_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(cams_ipcc, "Aridity/CMIP6/cams.ts_ipcc.txt")
```
```{r cams-monthly-long}
cams_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cams.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

camsm_land <- merge(cams_monthly, land_mask.df, by = c("lon", "lat")) 
camsm_ipcc <- merge(camsm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(camsm_ipcc, "Aridity/CMIP6/camsm.ts_ipcc.txt")
```

```{r cesm-annual-long}
cesm_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

cesm_land <- merge(cesm_annual, land_mask.df, by = c("lon", "lat")) 
cesm_ipcc <- merge(cesm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(cesm_ipcc, "Aridity/CMIP6/cesm.ts_ipcc.txt")
```

```{r cesm-monthly-long}
cesm_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cesm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

cesmm_land <- merge(cesm_monthly, land_mask.df, by = c("lon", "lat")) 
cesmm_ipcc <- merge(cesmm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(cesmm_ipcc, "Aridity/CMIP6/cesmm.ts_ipcc.txt")
```
```{r cmcc-annual-long}
cmcc_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

cmcc_land <- merge(cmcc_annual, land_mask.df, by = c("lon", "lat")) 
cmcc_ipcc <- merge(cmcc_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(cmcc_ipcc, "Aridity/CMIP6/cmcc.ts_ipcc.txt")
```

```{r cmcc-monthly-long}
cmcc_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cmcc.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

cmccm_land <- merge(cmcc_monthly, land_mask.df, by = c("lon", "lat")) 
cmccm_ipcc <- merge(cmccm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(cmccm_ipcc, "Aridity/CMIP6/cmccm.ts_ipcc.txt")
```

```{r cnrm-annual-long}
cnrm_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

cnrm_land <- merge(cnrm_annual, land_mask.df, by = c("lon", "lat")) 
cnrm_ipcc <- merge(cnrm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(cnrm_ipcc, "Aridity/CMIP6/cnrm.ts_ipcc.txt")
```

```{r cnrm-monthly-long}
cnrm_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/cnrm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

cnrmm_land <- merge(cnrm_monthly, land_mask.df, by = c("lon", "lat")) 
cnrmm_ipcc <- merge(cnrmm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(cnrmm_ipcc, "Aridity/CMIP6/cnrmm.ts_ipcc.txt")
```

```{r fgoals-annual-long}
fgoals_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

fgoals_land <- merge(fgoals_annual, land_mask.df, by = c("lon", "lat")) 
fgoals_ipcc <- merge(fgoals_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(fgoals_ipcc, "Aridity/CMIP6/fgoals.ts_ipcc.txt")
```

```{r fgoals-monthly-long}
fgoals_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/fgoals.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

fgoalsm_land <- merge(fgoals_monthly, land_mask.df, by = c("lon", "lat")) 
fgoalsm_ipcc <- merge(fgoalsm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(fgoalsm_ipcc, "Aridity/CMIP6/fgoalsm.ts_ipcc.txt")
```

```{r inm-annual-long}
inm_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

inm_land <- merge(inm_annual, land_mask.df, by = c("lon", "lat")) 
inm_ipcc <- merge(inm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(inm_ipcc, "Aridity/CMIP6/inm.ts_ipcc.txt")
```

```{r inm-monthly-long}
inm_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/inm.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

inmm_land <- merge(inm_monthly, land_mask.df, by = c("lon", "lat")) 
inmm_ipcc <- merge(inmm_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(inmm_ipcc, "Aridity/CMIP6/inmm.ts_ipcc.txt")
```

```{r mpi-annual-long}
mpi_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

mpi_land <- merge(mpi_annual, land_mask.df, by = c("lon", "lat")) 
mpi_ipcc <- merge(mpi_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(mpi_ipcc, "Aridity/CMIP6/mpi.ts_ipcc.txt")
```

```{r mpi-monthly-long}
mpi_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mpi.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

mpim_land <- merge(mpi_monthly, land_mask.df, by = c("lon", "lat")) 
mpim_ipcc <- merge(mpim_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(mpim_ipcc, "Aridity/CMIP6/mpim.ts_ipcc.txt")
```

```{r mri-annual-long}
mri_annual <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.ts.txt"), model = "historical", period = "1850_1880"),mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.ts.txt"), model = "historical", period = "1985_2015")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.ts.txt"), model = "SSP245", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.ts.txt"), model = "SSP245", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.ts.txt"), model = "SSP370", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.ts.txt"), model = "SSP370", period = "2070_2100")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.ts.txt"), model = "SSP585", period = "2030_2060")) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.ts.txt"), model = "SSP585", period = "2070_2100"))

mri_land <- merge(mri_annual, land_mask.df, by = c("lon", "lat")) 
mri_ipcc <- merge(mri_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(mri_ipcc, "Aridity/CMIP6/mri.ts_ipcc.txt")
```

```{r mri-monthly-long}
mri_monthly <- rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.jan.ts.txt"), model = "historical", period = "1850_1880", month = 1),mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.jan.ts.txt"), model = "historical", period = "1985_2015", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.jan.ts.txt"), model = "SSP245", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.jan.ts.txt"), model = "SSP245", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.jan.ts.txt"), model = "SSP370", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.jan.ts.txt"), model = "SSP370", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.jan.ts.txt"), model = "SSP585", period = "2030_2060", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.jan.ts.txt"), model = "SSP585", period = "2070_2100", month = 1)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.fev.ts.txt"), model = "historical", period = "1850_1880", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.fev.ts.txt"), model = "historical", period = "1985_2015", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.fev.ts.txt"), model = "SSP245", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.fev.ts.txt"), model = "SSP245", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.fev.ts.txt"), model = "SSP370", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.fev.ts.txt"), model = "SSP370", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.fev.ts.txt"), model = "SSP585", period = "2030_2060", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.fev.ts.txt"), model = "SSP585", period = "2070_2100", month = 2)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 3)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 4)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 5)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 6)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 7)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 8)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 9)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 10)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 11)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1850-1880.mar.ts.txt"), model = "historical", period = "1850_1880", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.hist.1985-2015.mar.ts.txt"), model = "historical", period = "1985_2015", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2030-2060.mar.ts.txt"), model = "SSP245", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp245.2070-2100.mar.ts.txt"), model = "SSP245", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2030-2060.mar.ts.txt"), model = "SSP370", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp370.2070-2100.mar.ts.txt"), model = "SSP370", period = "2070_2100", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2030-2060.mar.ts.txt"), model = "SSP585", period = "2030_2060", month = 12)) %>%
rbind(mutate(read.table("/bettik/crapartc/Averages/ts/mri.ssp585.2070-2100.mar.ts.txt"), model = "SSP585", period = "2070_2100", month = 12)) 

mrim_land <- merge(mri_monthly, land_mask.df, by = c("lon", "lat")) 
mrim_ipcc <- merge(mrim_land, ipcc_regions.df, by = c("lon", "lat"))

write.table(mrim_ipcc, "Aridity/CMIP6/mrim.ts_ipcc.txt")
```

```{r all-annual}
all_annual <- rbind(mutate(read.table("Aridity/CMIP6/awi.ts_ipcc.txt"), source = "AWI"),mutate(read.table("Aridity/CMIP6/bcc.ts_ipcc.txt"), source = "BCC")) %>%
rbind(mutate(read.table("Aridity/CMIP6/cams.ts_ipcc.txt"), source = "CAMS")) %>%
rbind(mutate(read.table("Aridity/CMIP6/cesm.ts_ipcc.txt"), source = "CESM")) %>%
rbind(mutate(read.table("Aridity/CMIP6/cmcc.ts_ipcc.txt"), source = "CMCC")) %>%
rbind(mutate(read.table("Aridity/CMIP6/cnrm.ts_ipcc.txt"), source = "CNRM")) %>%
rbind(mutate(read.table("Aridity/CMIP6/fgoals.ts_ipcc.txt"), source = "FGOALS")) %>%
rbind(mutate(read.table("Aridity/CMIP6/inm.ts_ipcc.txt"), source = "INM")) %>%
rbind(mutate(read.table("Aridity/CMIP6/mpi.ts_ipcc.txt"), source = "MPI")) %>%
rbind(mutate(read.table("Aridity/CMIP6/mri.ts_ipcc.txt"), source = "MRI"))

write.table(all_annual, "Aridity/ts.all_annual.txt")

```` 