---
title: "Visualisation awi"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
date: "2023-12-17"
bibliography: AI.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, error = F, fig.align = "center", collapse = T)
```

```{r libraries}
library(raster)
library(plyr)
library(dplyr)
library(ggplot2)
library(viridisLite)
library(sf)
library(stringr)
```

```{r data}
world.df <- readRDS("Worldclim/world.df.rds")
ts.all_annual <- read.table("CMIP6/ts/ts.all_annual.txt")
pr.all_annual <- read.table("CMIP6/pr/pr.all_annual.txt")
rsds.all_annual <- read.table("CMIP6/rsds/rsds.all_annual.txt") # units: W/m2
sfcWind.all_annual <- read.table("CMIP6/sfcWind/sfcWind.all_annual.txt")
```

```{r data-month}
ts_january <- read.table("CMIP6/ts/ts.all_january.txt") %>% select(!month) %>% rename(ts_01 = ts)
ts_february <- read.table("CMIP6/ts/ts.all_february.txt") %>% select(!month) %>% rename(ts_02 = ts)
ts_march <- read.table("CMIP6/ts/ts.all_march.txt") %>% select(!month) %>% rename(ts_03 = ts)
ts_april <- read.table("CMIP6/ts/ts.all_april.txt") %>% select(!month) %>% rename(ts_04 = ts)
ts_may <- read.table("CMIP6/ts/ts.all_may.txt") %>% select(!month) %>% rename(ts_05 = ts)
ts_june <- read.table("CMIP6/ts/ts.all_june.txt") %>% select(!month) %>% rename(ts_06 = ts)
ts_july <- read.table("CMIP6/ts/ts.all_july.txt") %>% select(!month) %>% rename(ts_07 = ts)
ts_august <- read.table("CMIP6/ts/ts.all_august.txt") %>% select(!month) %>% rename(ts_08 = ts)
ts_september <- read.table("CMIP6/ts/ts.all_september.txt") %>% select(!month) %>% rename(ts_09 = ts)
ts_october <- read.table("CMIP6/ts/ts.all_october.txt") %>% select(!month) %>% rename(ts_10 = ts)
ts_november <- read.table("CMIP6/ts/ts.all_november.txt") %>% select(!month) %>% rename(ts_11 = ts)
ts_december <- read.table("CMIP6/ts/ts.all_december.txt") %>% select(!month) %>% rename(ts_12 = ts)

ts_month <- ts_january %>% 
  merge(ts_february, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_march, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_april, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_may, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_june, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_july, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_august, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_september, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_october, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_november, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source")) %>%
    merge(ts_december, by =c("lon","lat","model","period","lm","Continent","Type","Name","Acronym","source"))

ts_month <- ts_month %>% rowwise() %>% mutate(ts_min = min(ts_01, ts_02, ts_03, ts_04, ts_05, ts_06, ts_07, ts_08, ts_09, ts_10, ts_11, ts_12)) %>% as.data.frame()
```

```{r proba-models}
v<-NULL
v2<-NULL
for (N in 10:100) {
  v<-c(v,sum(sapply(floor(2*N/3):N,function(i) choose(N,i)*(1/2)^N*2)))# proba d'avoir 2/3 de même signe à partir de N modèles, lorsque N change
  v2<-c(v2,sum(sapply(floor(2*N/3):N,function(i) choose(N,i)*(1/2)^N)))# proba d'avoir 2/3 de signe >0 à partir de N modèles, lorsque N change
}


plot(10:100,v,type="l",ylab="Proba(>2/3 models...)",xlab="Nb of models")
lines(10:100,v2,col="red")

legend("topright",c("même signe","signe >0"),col=c("black","red"),lty=1)

```

# Worldclim: réanalyse pour la période 1970-2000 -----

```{r worldclim}
cmcc <- raster("CMIP6/historical/ts/ts_Amon_CMCC-CM2-SR5_historical_r1i1p1f1_gn_185001-201412.nc")
crs(cmcc) <- "EPSG:4326"
cmcc.df <- as.data.frame(cmcc, xy = T)

wdct <- raster("Worldclim/wc2.1_10m/wc2.1_10m_bio_1.tif") 
crs(wdct) <- "EPSG:4326"
extent(wdct) <- extent(cmcc)
wdctt <- wdct %>% projectRaster(to = cmcc) %>% as.data.frame(xy = T) %>% setNames(c("lon","lat","ts"))

wdcp <- raster("Worldclim/wc2.1_10m/wc2.1_10m_bio_12.tif") 
crs(wdcp) <- "EPSG:4326"
extent(wdcp) <- extent(cmcc)
wdcpp <- wdcp %>% projectRaster(to = cmcc) %>% as.data.frame(xy = T) %>% setNames(c("lon","lat","pr"))

list.wind <- list.files(path = "Worldclim/wc2.1_10m/", pattern = "wc2.1_10m_wind", full.names = TRUE)
wdcw <- raster::stack(list.wind) %>% mean(na.rm = T)
crs(wdcw) <- "EPSG:4326"
extent(wdcw) <- extent(cmcc)
wdcww <- wdcw %>% projectRaster(to = cmcc) %>% as.data.frame(xy = T) %>% setNames(c("lon","lat","sfcWind"))

list.rsds <- list.files(path = "Worldclim/wc2.1_10m/", pattern = "wc2.1_10m_srad", full.names = TRUE) # unit: kJ/m2/day
wdcr <- raster::stack(list.rsds) %>% mean(na.rm = T)
crs(wdcr) <- "EPSG:4326"
extent(wdcr) <- extent(cmcc)
wdcrr <- wdcr %>% projectRaster(to = cmcc) %>% as.data.frame(xy = T) %>% setNames(c("lon","lat","rsds"))

elev <- raster("Worldclim/wc2.1_10m/wc2.1_10m_elev.tif") 
crs(elev) <- "EPSG:4326"
extent(elev) <- extent(cmcc)
elevation <- elev %>% projectRaster(to = cmcc) %>% as.data.frame(xy = T) %>% setNames(c("lon","lat", "z"))

land_mask <- raster("Masks/land_sea_mask_1degree.nc4") 
extent(land_mask) <- extent(cmcc)
land_mask <-  projectRaster(from = land_mask, to = cmcc)
land_mask.df <- as.data.frame(land_mask, xy = T) %>% setNames(c("lon","lat","lm")) # 0 if ocean, 1 if land

ipcc_regions <- shapefile("Masks/IPCC-WGI-reference-regions-v4.shp") %>% spTransform(crs("EPSG:4326")) 
ipcc_regions.raster <- ipcc_regions %>% rasterize(cmcc)
ipcc_regions.df <- as.data.frame(ipcc_regions.raster, xy = T) %>% setNames(c("lon","lat","Continent","Type","Name","Acronym"))

wdcttt <- wdctt %>% merge(land_mask.df, by = c("lon","lat")) %>% merge(ipcc_regions.df, by = c("lon","lat"))

ggplot(wdcttt)+
  geom_raster(aes(x = lon, y = lat, fill = ts))+
  scale_fill_distiller(type = "div", palette = 7, direction = -1, na.value = "white")+
  labs(fill = "Average annual surface temperature, °C")+
  theme_void()+
  theme(legend.position = "bottom")

wdcppp <- wdcpp %>% merge(land_mask.df, by = c("lon","lat")) %>% merge(ipcc_regions.df, by = c("lon","lat"))

ggplot(wdcppp)+
  geom_raster(aes(x = lon, y = lat, fill = pr))+
  scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom")

wdcwww <- wdcww %>% merge(land_mask.df, by = c("lon","lat")) %>% merge(ipcc_regions.df, by = c("lon","lat"))

ggplot(wdcwww)+
  geom_raster(aes(x = lon, y = lat, fill = sfcWind))+
  scale_fill_distiller(type = "seq", palette = 3, direction = 1, na.value = "white")+
  labs(fill = "Average annual wind speed, m/s")+
  theme_void()+
  theme(legend.position = "bottom")

wdcrrr <- wdcrr %>% merge(land_mask.df, by = c("lon","lat")) %>% merge(ipcc_regions.df, by = c("lon","lat"))

ggplot(wdcrrr)+
  geom_raster(aes(x = lon, y = lat, fill = rsds))+
  scale_fill_distiller(type = "seq", palette = 7, direction = 1, na.value = "white")+
  labs(fill = "Average annual irradiation")+
  theme_void()+
  theme(legend.position = "bottom")
```

# Boxplots of ts, pr, rsds and sfcWind from CMIP6 compared to Worldclim -----

```{r test-awi_future, eval = F}
ggplot(subset(awi.ts_ipcc, Acronym %in% c("WCE", "MED")))+geom_boxplot(aes(x=period, y = ts-273, col = model))+
      facet_grid(cols = vars(Name))+scale_color_viridis_d(option = "A", end = 0.8)+
      labs(x = "", y = "Average annual temperature, °C") + theme_minimal()

ggplot(subset(awi.ts_ipcc, Acronym %in% c("WAF")))+geom_boxplot(aes(x=period, y = ts-273, col = model))+
      facet_grid(cols = vars(Name))+scale_color_viridis_d(option = "A", end = 0.8)+
       labs(x = "", y = "Average annual temperature, °C") + theme_minimal()

ggplot(subset(awi.ts_ipcc, model == "SSP585" & period == "2070_2100" & lm != 0))+
  geom_raster(aes(x = lon, y = lat, fill = ts-273))+
  scale_fill_distiller(type = "div", palette = 7, direction = -1)+
  labs(fill = "Average annual surface temperature, °C")+
  theme_void()+
  theme(legend.position = "bottom")

ggplot(subset(awi.ts_ipcc, model == "SSP585" & period == "2070_2100"))+
  geom_raster(aes(x = lon, y = lat, fill = ts-273))+
  scale_fill_distiller(type = "div", palette = 7, direction = -1)+
  labs(fill = "Average annual surface temperature, °C")+
  theme_void()+
  theme(legend.position = "bottom")

ggplot(subset(awi.ts_ipcc, model == "SSP585" & period == "2070_2100" & lm > 0 & lm < 1))+
  geom_raster(aes(x = lon, y = lat, fill = ts-273))+
  scale_fill_distiller(type = "div", palette = 7, direction = -1)+
  labs(fill = "Average annual surface temperature, °C")+
  theme_void()+
  theme(legend.position = "bottom")
```

```{r all_future}
ggplot()+geom_boxplot(data = subset(ts.all_annual, period == "1970_2000"), aes(x=source, y = ts-273, col = source))+
    geom_boxplot(data = wdcttt, aes(x="Worldclim", y = ts, col = "Worldclim"))+
     scale_color_viridis_d(option = "A", end = 0.8)+
     labs(x = "", y = "Average annual temperature, °C") + theme_minimal()

ggplot()+geom_boxplot(data = subset(pr.all_annual, period == "1970_2000"), aes(x=source, y = pr*60*60*24*365, col = source))+ # conversion from kg/m2/s to mm/year
    geom_boxplot(data = wdcppp, aes(x="Worldclim", y = pr, col = "Worldclim"))+
     scale_color_viridis_d(option = "A", end = 0.8)+
     labs(x = "", y = "Average annual precipitation, mm") + theme_minimal()

ggplot()+geom_boxplot(data = subset(rsds.all_annual, period == "1970_2000"), aes(x=source, y = rsds, col = source))+
    geom_boxplot(data = wdcrrr, aes(x="Worldclim", y = rsds*1000/86400, col = "Worldclim"))+ # conversion from kJ/m2/day to W/m2 (1 J = 1 W.s)
     scale_color_viridis_d(option = "A", end = 0.8)+
     labs(x = "", y = "Average annual precipitation, kJ/m2/d") + theme_minimal()

ggplot()+geom_boxplot(data = subset(sfcWind.all_annual, period == "1970_2000"), aes(x=source, y = sfcWind, col = source))+
    geom_boxplot(data = wdcwww, aes(x="Worldclim", y = sfcWind, col = "Worldclim"))+
     scale_color_viridis_d(option = "A", end = 0.8)+
     labs(x = "", y = "Average annual wind speed, m/s") + theme_minimal()

```

```{r merge}
clim <- ts.all_annual %>% 
  merge(ts_month, by = c("lon","lat","model","period","lm", "Continent","Type","Name","Acronym","source")) %>%
  merge(pr.all_annual, by = c("lon","lat","model","period","lm", "Continent","Type","Name","Acronym","source")) %>%
  merge(rsds.all_annual, by = c("lon","lat","model","period","lm", "Continent","Type","Name","Acronym","source")) %>%
  merge(sfcWind.all_annual, by = c("lon","lat","model","period","lm", "Continent","Type","Name","Acronym","source")) %>% 
  merge(elevation, by = c("lon","lat"))
# as minimum temperature we use the minimum monthly average
```

```{r aridity-index}
clim$AIm <- with(clim,pr*60*60*24*365/(ts-273.15+10)) # pr in mm/y, ts in Ceslsius
breaks.martonne <- c(0,5,10,20,"30","40",Inf)
cat.martonne <- c("[0,5]" = "Desert", "(5,10]"= "Arid", "(10,20]" = "Semi-arid","(20,30]" = "Temperate", "(30,40]" = "Humid", "(40,Inf]" = "Forest")
col.martonne <- c("Desert" = colorvec[1], "Arid"= colorvec[2],"Semi-arid"= colorvec[3], "Temperate" = colorvec[4], "Humid"= colorvec[5],"Forest"= colorvec[6])
clim$cat.AIm <- clim$AIm %>% cut(breaks.martonne, include.lowest = T) %>% revalue(cat.martonne)

clim$P <- with(clim, 101.3 * ((293-0.0065*z)/293)^(5.26))
clim$es <- with(clim, ifelse((ts-273.15) > 0, 0.61078*exp(17.27*(ts-273.15)/((ts-273.15)+237.3)),  0.61078*exp(21.875*(ts-273.15)/((ts-273.15)+265.5)))) # saturation vapor pressure Monteith-Unsworth pour >0, Murray pour T < 0
clim$delta <- with(clim, 4098*es/((ts-273.15)+237.3)^2) #slope vapor pressure
clim$gamma <- with(clim, 0.00163*P/(2.501-52.6361e-3*(ts-273.15))) #psychrometric constant
clim$ea <- with(clim, with(clim, ifelse((ts_min-273.15) > 0, 0.61078*exp(17.27*(ts_min-273.15)/((ts_min-273.15)+237.3)),  0.61078*exp(21.875*(ts_min-273.15)/((ts_min-273.15)+265.5))))) # actual vapor pressur; when relative humidity is not availabmle, ea is obtained by estimating that when the air temp is close to Tmin, it is nearly saturated
clim$ET0 <-with(clim, ((0.408*delta*(rsds*86400*1e-6)+gamma*900/((ts-273.15)+273)*sfcWind*(es-ea))/(delta+gamma*(1+0.34*sfcWind)))) # Evapotranspiration, G considered to be negligible. in mm/day. Irradiation is in W/m2 and is converted to MJ/m2/day
clim$AIu <- with(clim, pr*60*60*24*365/(ET0*365))

breaks.unesco <- c(0,0.03,0.2,0.5,0.65,Inf)
cat.unesco <- c("[0,0.03]"= "Hyperarid", "(0.03,0.2]" = "Arid", "(0.2,0.5]" = "Semi-arid", "(0.5,0.65]" = "Dry subhumid","(0.65,Inf]" = "Humid")
col.cat <- c("Hyperarid" = colorvec[1], "Arid"= colorvec[2],"Semi-arid"= colorvec[3], "Dry subhumid" = colorvec[4], "Humid"= colorvec[5])

clim$cat.AIu <- clim$AIu %>% cut(breaks = breaks.unesco) %>% 
  revalue(cat.unesco)


clim_sum <- clim %>% group_by(lon, lat, model, period) %>% dplyr::summarise(ts = mean(ts, na.rm = T), pr = mean(pr, na.rm = T), AIm = mean(AIm, na.rm = T), AIu = mean(AIu, na.rm = T))
clim_sum$cat.AIu <- clim_sum$AIu %>% cut(breaks = breaks.unesco) %>% 
  revalue(cat.unesco)
clim_sum$cat.AIm <- clim_sum$AIm %>% cut(breaks = breaks.martonne) %>% 
  revalue(cat.martonne)
write.table(clim_sum, "clim_sum.txt")
```


```{r plot}

ggplot() + geom_raster(data = subset(clim_sum, period == "1970_2000" & AIm >= 0), aes(x=lon, y = lat,  fill = cat.AIm))+
  geom_raster(data = subset(clim_sum, period == "1970_2000" & AIm < 0), aes(x=lon, y = lat), fill = "gray60")+
    scale_fill_manual(values = col.martonne)+
         theme_void()+
   theme(legend.position = "bottom")

ggplot() + geom_raster(data = subset(clim, period == "1970_2000" & source == "CNRM"), aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
         theme_void()+
   theme(legend.position = "bottom")

```

# Plots for AI -----

```{r mean-by-period-SSP245}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "Historical, 1850-1880", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "Historical, 1970-2000", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

# ggplot(data = subset(clim_sum, period == "1985_2015")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
#     scale_fill_manual(values = col.cat)+
#     labs(title = "Historical, 1985-2015", fill = "")+
#     theme_void()

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP245")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "SSP245, 2030-2060", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")
ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP245")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "SSP245, 2070-2100", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")
```
```{r mean-by-period-SSP370}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "Historical, 1850-1880", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "Historical, 1970-2000", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

# ggplot(data = subset(clim_sum, period == "1985_2015")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
#     scale_fill_manual(values = col.cat)+
#     labs(title = "Historical, 1985-2015", fill = "")+
#     theme_void()

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "SSP370, 2030-2060", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "SSP370, 2070-2100", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")
```
```{r mean-by-period-SSP585}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "Historical, 1850-1880", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "Historical, 1970-2000", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

# ggplot(data = subset(clim_sum, period == "1985_2015")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
#     scale_fill_manual(values = col.cat)+
#     labs(title = "Historical, 1985-2015", fill = "")+
#     theme_void()

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP585")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "SSP585, 2030-2060", fill = "")+
    theme_void()
ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP585")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
    scale_fill_manual(values = col.cat)+
    labs(title = "SSP585, 2070-2100", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")
```

# Plots for ts ----

```{r mean-by-period-SSP245-ts}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "Historical, 1850-1880", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "Historical, 1970-2000", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP245")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "SSP245, 2030-2060", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP245")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "SSP245, 2030-2060", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")
```

```{r mean-by-period-SSP370-ts}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "Historical, 1850-1880", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "Historical, 1970-2000", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "SSP370, 2030-2060", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "SSP370, 2030-2060", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")
```

```{r mean-by-period-SSP585-ts}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "Historical, 1850-1880", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "Historical, 1970-2000", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP585")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
    scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "SSP585, 2030-2060", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP585")) + geom_raster(aes(x=lon, y = lat,  fill = ts-273.15))+
scale_fill_distiller(type = "div", palette = 7, direction = -1, limits = c(-60,35))+
    labs(title = "SSP585, 2030-2060", fill = "Average annual surface temperature, °C")+
    theme_void()+
   theme(legend.position = "bottom")
```

# Plots for pr ----

```{r mean-by-period-SSP245-pr}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "Historical, 1850-1880", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 
  

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,   fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "Historical, 1970-2000", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP245")) + geom_raster(aes(x=lon, y = lat, fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "SSP245, 2030-2060", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP245")) + geom_raster(aes(x=lon, y = lat,   fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "SSP245, 2070-21000", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 
```

```{r mean-by-period-SSP370-pr}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "Historical, 1850-1880", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 
  

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,   fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "Historical, 1970-2000", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat, fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "SSP370, 2030-2060", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat,   fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "SSP370, 2070-21000", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 
```

```{r mean-by-period-SSP585-pr}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "Historical, 1850-1880", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 
  

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,   fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "Historical, 1970-2000", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP585")) + geom_raster(aes(x=lon, y = lat, fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "SSP585, 2030-2060", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP585")) + geom_raster(aes(x=lon, y = lat,   fill = pr*60*60*24*365))+
    scale_fill_distiller(type = "seq", palette = 1, direction = 1, na.value = "white")+
  labs(title = "SSP585, 2070-21000", fill = "Average annual precipitation, mm")+
  theme_void()+
  theme(legend.position = "bottom") 
```

# Plots AI martonne

```{r mean-by-period-SSP370}
ggplot(data = subset(clim_sum, period == "1850_1880")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIm))+
    scale_fill_manual(values = col.martonne, na.value = "gray")+
    labs(title = "Historical, 1850-1880", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "1970_2000")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIm))+
    scale_fill_manual(values = col.martonne, na.value = "gray")+
    labs(title = "Historical, 1970-2000", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

# ggplot(data = subset(clim_sum, period == "1985_2015")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIu))+
#     scale_fill_manual(values = col.cat)+
#     labs(title = "Historical, 1985-2015", fill = "")+
#     theme_void()

ggplot(data = subset(clim_sum, period == "2030_2060" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIm))+
    scale_fill_manual(values = col.martonne, na.value = "gray")+
    labs(title = "SSP370, 2030-2060", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")

ggplot(data = subset(clim_sum, period == "2070_2100" & model == "SSP370")) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIm))+
    scale_fill_manual(values = col.martonne, na.value = "gray")+
    labs(title = "SSP370, 2070-2100", fill = "")+
    theme_void()+
   theme(legend.position = "bottom")
```

```{r plot-historical-AIm-by-model}
for(i in unique(clim$source)){
plottitle <- paste(i, "historical, 1970-2000", sep = ", ")
g <- ggplot(data = filter(clim, period == "1970_2000" & source == i)) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIm))+
    scale_fill_manual(values = col.martonne, na.value = "gray")+
    labs(title = plottitle, fill = "")+
    theme_void()+
   theme(legend.position = "bottom")
print(g)
}
```

```{r plot-SSP370-AIm-by-model}
for(i in unique(clim$source)){
plottitle <- paste(i, "SSP370, 2070-2100", sep = ", ")
g <- ggplot(data = filter(clim, period == "2070_2100" & model = "SSP370" & source == i)) + geom_raster(aes(x=lon, y = lat,  fill = cat.AIm))+
    scale_fill_manual(values = col.martonne, na.value = "gray")+
    labs(title = plottitle, fill = "")+
    theme_void()+
   theme(legend.position = "bottom")
print(g)
}
``` 